USE doanjava
create table CanHo(
MACANHO CHAR(10) NOT NULL PRIMARY KEY,
SODAY CHAR(10) NOT NULL,
TENCHUHO VARCHAR(40) NOT NULL,
TRANGTHAI VARCHAR(20) NOT NULL,
DIENTICH char(10) NOT NULL,
SONGUOI INT NOT NULL,
SODIEN INT NOT NULL,
SONUOC INT NOT NULL)
