use doanjava
CREATE TABLE CuDan1(
MACUDAN CHAR(10) NOT NULL PRIMARY KEY,
TENCUDAN NVARCHAR(50) NOT NULL,
GIOITINH NVARCHAR(10) NOT NULL,
NGAYSINH char(20) NOT NULL,
CCCD CHAR(20) NOT NULL,
SDT CHAR(20) NOT NULL,
NGAYDK char(20) NOT NULL,
MACANHO CHAR(10) NOT NULL,
)

