USE doanjava
create table THANHTOAN(
THANG CHAR(10) NOT NULL,
MAHD CHAR(10) NOT NULL PRIMARY KEY,
MACANHO CHAR(10) NOT NULL,
TIENDIEN CHAR(20) NOT NULL,
TIENNUOC CHAR(20) NOT NULL,
TIENPHONG CHAR(20) NOT NULL,
GUIXE CHAR(20) NOT NULL,
TONG CHAR(30) NOT NULL,
TRANGTHAI NVARCHAR(30) NOT NULL,
CONSTRAINT FK_THANHTOAN_CanHo_MACANHO FOREIGN KEY (MACANHO) REFERENCES CanHo
)