USE doanjava
CREATE TABLE TRUONGPHONG(
MACUDAN CHAR(10) NOT NULL PRIMARY KEY,
TENCUDAN NVARCHAR(50) NOT NULL,
GIOITINH NVARCHAR(10) NOT NULL,
NGAYSINH CHAR(20) NOT NULL,
CCCD CHAR(20) NOT NULL,
SDT CHAR(20) NOT NULL,
NGAYDK CHAR(20) NOT NULL,
MACANHO CHAR(10) NOT NULL,
CONSTRAINT FK_TRUONGPHONG_CanHo_MACANHO FOREIGN KEY (MACANHO) REFERENCES CanHo)